# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSeleniumtestitemnumbers():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_seleniumtestitemnumbers(self):
    self.driver.get("https://www.saucedemo.com/")
    self.driver.set_window_size(1366, 768)
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"username\"]")))
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"password\"]")))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").send_keys("standard_user")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys("secret_sauce")
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"login-button\"]")))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".inventory_item:nth-child(1) > .inventory_item_description")))
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".inventory_item:nth-child(2) > .inventory_item_description")))
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".inventory_item:nth-child(3) > .inventory_item_description")))
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".inventory_item:nth-child(4) > .inventory_item_description")))
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".inventory_item:nth-child(5) .inventory_item_desc")))
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".inventory_item:nth-child(6) > .inventory_item_description")))
  
